
format: ## Format the whole project
	fvm dart format .
analyze: ## Runs linting
	fvm flutter analyze
	fvm dart format .
apk:
	fvm flutter build apk  .
aab:
	fvm flutter build appbundle --release
ipa:
	fvm flutter build ipa
launch-icons:
	fvm flutter pub run flutter_launcher_icons -f flutter_launcher_icons-$(colegio)