name: epub_parser
description: Epub Parser for Dart. Created by Everwise.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^3.1.6
  quiver: ^3.0.1+1
  path: ^1.8.1
  xml: ^6.0.1
  image: ^4.0.17
  collection: ^1.15.0
  equatable: ^2.0.5
  image_size_getter: ^2.2.0
  csslib: ^1.0.2
dev_dependencies:
  test: ^1.16.7
  path: ^1.8.0
  pedantic: ^1.11.0
